name: stock_calculator
description: 간단하고 좋은 주식 계산기입니다.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  google_mobile_ads: ^0.13.0
  number_slide_animation: ^0.2.1
  provider: ^5.0.0
  intl: ^0.16.1
  carousel_slider: ^4.0.0
  auto_size_text_pk: ^3.0.0
  # intro_slider: ^3.0.2
  # dots_indicator: ^2.0.0
  flutter_image_slideshow: ^0.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon3.png"
  # adaptive_icon_background: #43c89f
  # adaptive_icon_foreground: #43c89f

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:

    - family: GmarketSansMedium
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf

    - family: Cafe24
      fonts:
        - asset: assets/fonts/Cafe24Oneprettynight.ttf

    - family: Jeju
      fonts:
        - asset: assets/fonts/JejuHallasan.ttf

    
    - family: Cafe24Simplehae
      fonts:
        - asset: assets/fonts/Cafe24Simplehae.ttf
