name: stock_calculator
description: 간단하고 좋은 주식,코인 계산기입니다.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  google_mobile_ads: ^0.13.0
  number_slide_animation: ^0.2.1
  provider: ^5.0.0
  intl: ^0.16.1
  carousel_slider: ^4.0.0
  auto_size_text_pk: ^3.0.0
  # intro_slider: ^3.0.2
  # dots_indicator: ^2.0.0
  flutter_image_slideshow: ^0.1.0
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/grad.png"
  image_path_android: "assets/icon/grad.png"
  adaptive_icon_background: "assets/icon/grad.png"
  adaptive_icon_foreground: "assets/icon/grad.png"

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:

    - family: GmarketSansMedium
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf

    - family: Cafe24
      fonts:
        - asset: assets/fonts/Cafe24Oneprettynight.ttf

    - family: Jeju
      fonts:
        - asset: assets/fonts/JejuHallasan.ttf

    
    - family: Cafe24Simplehae
      fonts:
        - asset: assets/fonts/Cafe24Simplehae.ttf

    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Thin.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Light.otf

    - family: S-Core_Dream
      fonts:
        - asset: assets/fonts/S-Core_Dream_OTF/SCDream3.otf
        - asset: assets/fonts/S-Core_Dream_OTF/SCDream2.otf
          weight: 100
        - asset: assets/fonts/S-Core_Dream_OTF/SCDream1.otf
          weight: 200